### ISSUE TITLE
显卡配置

### ISSUE THREAD

**Issue by zi1zi** [LambdaLabsML/examples#15]
您好，想训练模型的话，最低配置是多少呀

**Comment by justinpinkney** [comment]
I think a GPU with >24GB of VRAM is required for training.

**Comment by justinpinkney** [comment]
Turn down the batch size to 3 and I think it should work

**Comment by zi1zi** [comment]
您好，数据集是按照您pokemon.yaml中的target: ldm.data.simple.hf_dataset去下载吗，会下载到项目中哪里的

**Comment by zi1zi** [comment]
您好，我这有两块显存分别为11GB的可以吗，同时使用两块GPU只需要在训练时--gpus=0,1和n_gpus=2吗

**Comment by lioo717** [comment]
> @zi1zi 不行的，必须单块大于 24G

24G的不行，对吗？

**Comment by mingyao743** [comment]
> > @zi1zi 不行的，必须单块大于 24G
> 
> 24G的不行，对吗？

我试了，2快24g卡，应该不行

**Comment by devonbrackbill** [comment]
I ran into this issue. Many images are in RGBA format (4 channels), but the model expects RGB format (3 channels). Typically, the last channel (A) is the opacity/alpha. Depending on your use case you can just drop this channel.
```
import cv2
img = cv2.imread('image.png', cv2.IMREAD_UNCHANGED)
if img.shape[2] == 4:
  img = img[:, :, :3]  # remove the last channel
```
