### ISSUE TITLE
Can not reproduce the result

### ISSUE THREAD

**Issue by WuZifan** [LambdaLabsML/examples#17]
I try to reproduce the performance on Pokemon dataset with training configs like:
          python main.py     
          -t     
          --base configs/stable-diffusion/pokemon.yaml     
          --gpus 4,5,6,7     
          --scale_lr False     
          --num_nodes 1     
          --check_val_every_n_epoch 10     
          --finetune_from ./weights/sd-v1-4-full-ema.ckpt     
          data.params.batch_size="1"     
          lightning.trainer.accumulate_grad_batches="2"     
          data.params.validation.params.n_gpus="4"

but the generated images seem nothing but chaos after 200 epochs.
here are some results

yoda
<img width="514" alt="image" src="https://user-images.githubusercontent.com/22706545/194993986-e40af353-95f2-41a8-924d-154289dcf3d1.png">

A cute bunny rabit
<img width="527" alt="image" src="https://user-images.githubusercontent.com/22706545/194993861-65271543-fa13-4585-b3ec-1cdff7b7a8ac.png">
 
any suggestions?

**Comment by WuZifan** [comment]
> Are you using EMA version for inference?



the results image is from validation, and I also do the inference by:

python scripts/txt2img.py \
    --prompt 'robotic cat with wings' \
    --outdir 'outputs/generated_pokemon' \
    --H 512 --W 512 \
    --n_samples 4 \
    --config 'configs/stable-diffusion/pokemon_customer.yaml'  \
    --ckpt 'logs/2022-10-10T11-20-27_pokemon_customer/checkpoints/epoch=000114.ckpt'

not sure if I use the ema version, but the result still not good.

'robotic cat with wings

<img width="556" alt="image" src="https://user-images.githubusercontent.com/22706545/195010059-e31f35ee-2615-4509-94d7-b93e48f72d99.png">

**Comment by justinpinkney** [comment]
Hmmm, those do look more like the non-ema samples, but the txt2img script should use ema by default. 

I think my best checkpoint was at 170 epochs, so doesn't seem like it was trained too long.

Not sure what else it could be, are you using the same dataset?

**Comment by hypknot74** [comment]
I experimented with the same setup as pokemon.yaml in my data set and got the same phenomenon.
Similar objects are continuously generated in an image.

**Comment by hypknot74** [comment]
I solved this problem.
I had inadvertently changed the image_transforms size and output_size to 256 in the YAML file, but after correcting them to 512, I was able to reproduce the results correctly.

**Comment by WuZifan** [comment]
> 

the input image size is one of the key problems, another is the batch_size or accumulate_grad_batches;
since my gpu only has 32GB, i cant use batch_size=4 as mentioned in the repo. and accumulate_grad_batches=2 is still too small for the model to learn. After changing the accumulate_grad_batches to 4, i can have the expected result.

Thank you all~

**Comment by WuZifan** [comment]
> Hmmm, those do look more like the non-ema samples, but the txt2img script should use ema by default.
> 
> I think my best checkpoint was at 170 epochs, so doesn't seem like it was trained too long.
> 
> Not sure what else it could be, are you using the same dataset?

yes, just use the dataset on hugging face as mentioned in this repo. I found 2 errors in my config ,one is the input image size, i change it to 256 to reduce gpu-memory cost(which is not useful), and the other one is accumulate_batch_size, since i set batch_size to 1 to fit my gpu-memory size, the accumulate_batch_size should be relatively large to get a good result, for me ,4 is quite good.

**Comment by gstswwx** [comment]
The model produced the same pictures with the config "batch_size=1, accumulate_grad_batches=4, resize the input image to 256 * 256". But resizing the input image to 512 * 512 will cause CUDA out of memory. Can anyone help me?

![grid-0020](https://user-images.githubusercontent.com/21003094/196839353-7e85e4e1-8eb8-4e0b-8516-ad973676d2cf.png)
