### ISSUE TITLE
SD-Fine-Tune, "Caught TypeError in DataLoader"

### ISSUE THREAD

**Issue by treksis** [LambdaLabsML/examples#38]
Hi, I have tried to run the notebook code on Colab with your pokemon dataset, and it was generating the checkpoint.
I tried with my own dataset with only 5 images to test out before I jump into with my own 100k+ images, but I get two TypeErrors. Everything looks fine because your ```hf_dataset()``` function does the heavy lifting. 

```
https://huggingface.co/datasets/treksis/test_pinkeyrepo
```

![image](https://user-images.githubusercontent.com/54779707/200969127-1971dc0a-00b8-4930-9c5b-4bc973a2a551.png)

TypeError: Caught TypeError in DataLoader worker process 0

![image](https://user-images.githubusercontent.com/54779707/200969095-45529131-e9ea-4ce2-a2ae-d0cd299d8f2f.png)

TypeError: img should be PIL Image. Got <class 'dict'>

![image](https://user-images.githubusercontent.com/54779707/200966335-234f6425-716f-4653-8a08-93ae1080865f.png)

**Comment by willjejones** [comment]
+1 to this. I've got exactly the same TypeError with my own dataset:

```
File "/usr/lib/python3/dist-packages/torchvision/transforms/functional_pil.py", line 249, in resize
    raise TypeError(f"img should be PIL Image. Got {type(img)}")
TypeError: img should be PIL Image. Got <class 'dict'>
```

**Comment by treksis** [comment]
Solved. Used TheLastBen's repo to re-install all the packages need.

https://github.com/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by AmanK1202** [comment]
Did you use the new model instead. stable-diffusion-v1-5?

**Comment by Conaire** [comment]
@treksis is there a way to get a ckpt file from this?

**Comment by treksis** [comment]
you can always use diffusers libraries. Go to diffusers- > scripts- > covert diffuser to ckpt

**Comment by Conaire** [comment]
will try that out, here is the link for anyone else that might want it: https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py

**Comment by treksis** [comment]
it works i did and i used in auto1111's webui

**Comment by Conaire** [comment]
Sweet, thanks.

**Comment by fengchuanpeng** [comment]
@treksis hello ,I would like to ask you how to solve this problem .TypeError: img should be PIL Image. Got <class 'dict'>
