### ISSUE TITLE
wrong number of channels

### ISSUE THREAD

**Issue by Johann4DL** [LambdaLabsML/examples#39]
When I run the code with my own data, I run into this error:

RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[3, 1, 512, 512] to have 3 channels, but got 1 channels instead

First I thought, that my images might be grayscaled (not RGB) and thus have only one channel instead of 3, but this doesn't seem to be the case. Any ideas on how to solve the issue?

**Comment by lvsi-qi** [comment]
Do you solve it?

**Comment by lvsi-qi** [comment]
Could you help me? I will thank you very much!

**Comment by kushinm** [comment]
Also pinging this, I seem to be getting the same issue
