### ISSUE TITLE
killed when epoch 0 finished

### ISSUE THREAD

**Issue by tengshaofeng** [LambdaLabsML/examples#41]
@justinpinkney @stephenbalaban @jmhummel @eolecvk 
appreciated for your great work. So amazing.
When I run training code, I got the error:
Epoch 0: 100%|█| 209/209 [06:12<00:00,  1.78s/it, loss=0.0685, v_num=0, train/loss_simple_step=0.0223, train/loss_vlb_step=8.78e-5, train/loss_step=0.0223, global_step=208.0,
Summoning checkpoint.
Killed

what is wrong. help me. thanks

**Comment by tengshaofeng** [comment]
on_train_epoch_end

**Comment by tengshaofeng** [comment]
When I resume from sd-v1-4.ckpt , it is ok for saving checkpoint. But when I resume from sd-v1-4-full-ema.ckpt, it failed when saving checkpoint.  Why? @justinpinkney

**Comment by justinpinkney** [comment]
Hmmm, `killed` usually means you ran out of system memory, which would make sense as the full-ema checkpoint is much larger.
