### ISSUE TITLE
Typo in finetuning example: parms -> params

### ISSUE THREAD

**Issue by hopibel** [LambdaLabsML/examples#6]
In pokemon_finetune.ipynb the "Run training" cell contains:
```
    data.params.validation.parms="$NUM_GPUS" \
```

Note it says `validation.parms` instead of `validation.params`

**Comment by justinpinkney** [comment]
Awesome, thanks for picking this up ❤️. Will fix it now!

**Comment by rsomani95** [comment]
@justinpinkney I had to add `n_gpus` as follows to get it to work:

```bash
data.params.validation.parms.n_gpus="$NUM_GPUS"
```

**Comment by justinpinkney** [comment]
🤦 ok, now fixed
